# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170425_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
